Update roll.py
opendwellers/jujubot pull request #17
Opened 2020-09-22 19:20 UTC by philippesasseville

roulette russe game implementation

2020-09-22 19:34 UTC, zortok requested changes

2020-09-22 19:34 UTC, zortok commented on plugins/roll.py
> +    elif number > 2:
```suggestion
    elif number > 1:
```
S'pas nécessaire. Tu check déjà number == 1

2020-09-22 19:34 UTC, zortok commented on plugins/roll.py
>          message.reply(number + ' is not a valid number for roll command')
```suggestion
        message.reply('{number} is not a valid number for roll command'.format(number=number))
```
Faudrait aussi corriger la unhandled exception

2021-03-22 21:27 UTC, gravufo approved these changes

2021-03-22 21:28 UTC, merged